# -*- coding: utf-8 -*-
"""
link-action.py

Arkswift Semrush Backlink Action Engine
========================================

Purpose
-------
Read the intelligence database generated by link-read.py / semrush_backlink_matrix.py
and convert referring-domain intelligence into an ACTIONABLE backlink acquisition queue.

This script deliberately separates two questions:

1) Acquisition path / execution priority:
   P0 = self-serve / immediate submission or profile/listing creation
   P1 = official contact / application / partner / contributor route
   P2 = cold outreach / editorial pitch
   P3 = strategic / high-effort backlink opportunity
   Drop = technical residue / redirect / asset / non-actionable crawl noise

2) Opportunity value:
   machine score based on Semrush authority/page quality, competitor overlap,
   live/follow structure, and OPTIONAL Semrush traffic enrichment.

IMPORTANT:
- P0/P1/P2/P3 is NOT decided by authority alone.
- A low-AS site can still be P0 if it is immediately executable.
- A very high-authority media/integration target can be P3 because acquisition is strategic.
- Missing traffic data is treated as UNKNOWN, not zero, and does not unfairly penalize a domain.

Expected files
--------------
Workspace/
    link-read.py
    link-action.py
    semrush_backlink_intelligence.db
    data/
    traffic/                         # optional
        *.csv / *.tsv / *.xlsx      # Semrush Bulk Analysis / Domain Overview exports
    reports/

Primary output
--------------
reports/Backlink_Action_Queue_P0-P3_YYYY-MM-DD.xlsx
reports/Backlink_Action_Queue_P0-P3_YYYY-MM-DD.csv
reports/Semrush_Traffic_Enrichment_Domains_YYYY-MM-DD.txt

Dependencies
------------
pip install openpyxl
"""

import os
import re
import csv
import json
import math
import glob
import sqlite3
import datetime
from collections import defaultdict, Counter
from statistics import mean
from urllib.parse import urlparse

try:
    import openpyxl
    from openpyxl import Workbook, load_workbook
    from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.datavalidation import DataValidation
    from openpyxl.formatting.rule import CellIsRule
    HAS_OPENPYXL = True
except ImportError:
    HAS_OPENPYXL = False


# ============================================================
# Configuration
# ============================================================
WORKSPACE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_FILE = os.path.join(WORKSPACE_DIR, "semrush_backlink_intelligence.db")
TRAFFIC_DIR = os.path.join(WORKSPACE_DIR, "traffic")
REPORT_DIR = os.path.join(WORKSPACE_DIR, "reports")

MAX_SAMPLE_LINKS = 10
HIGH_PAGE_AS_THRESHOLD = 40

PRIORITY_RANK = {
    "P0": 0,
    "P1": 1,
    "P2": 2,
    "P3": 3,
    "Drop": 4,
}

PRIORITY_LABEL = {
    "P0": "P0｜马上执行：自助提交/注册/主页/Listing",
    "P1": "P1｜官方入口：Contact/Application/Partner",
    "P2": "P2｜冷邮件：编辑/资源页/文章更新/Guest Post",
    "P3": "P3｜战略型：Integration/Media/PR/生态合作",
    "Drop": "Drop｜技术残留/跳转/静态资源/不可执行",
}

PRIORITY_COLORS = {
    "P0": "70AD47",
    "P1": "5B9BD5",
    "P2": "FFC000",
    "P3": "8064A2",
    "Drop": "A6A6A6",
}

COLOR_DARK = "1F4E78"
COLOR_MACHINE = "7F8C8D"
COLOR_INTEL = "44546A"
COLOR_AI = "70AD47"
COLOR_HUMAN = "4472C4"
COLOR_SCORE = "C55A11"
COLOR_LIGHT = "F2F2F2"
COLOR_RED = "C00000"
COLOR_WHITE = "FFFFFF"


# ============================================================
# Utility helpers
# ============================================================
def safe_float(value, default=0.0):
    try:
        if value is None or str(value).strip() == "":
            return default
        text = str(value).replace(",", "").replace("%", "").strip()
        return float(text)
    except (ValueError, TypeError):
        return default


def safe_int(value, default=0):
    try:
        if value is None or str(value).strip() == "":
            return default
        return int(float(str(value).replace(",", "").strip()))
    except (ValueError, TypeError):
        return default


def normalize_header(text):
    text = str(text or "").replace("\ufeff", "").strip().lower()
    text = re.sub(r"[\s_\-()/]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()


def clean_domain(value):
    text = str(value or "").strip().lower()
    if not text:
        return ""
    if "://" not in text:
        text = "https://" + text
    try:
        host = (urlparse(text).hostname or "").strip(".").lower()
    except Exception:
        host = str(value or "").strip().lower()
    if host.startswith("www."):
        host = host[4:]
    return host


def url_path(url):
    try:
        parsed = urlparse(str(url or ""))
        return (parsed.path or "").lower()
    except Exception:
        return ""


def is_follow(row):
    return int(not (row.get("is_nofollow") or row.get("is_sponsored") or row.get("is_ugc")))


def pct(numerator, denominator):
    return numerator / denominator if denominator else 0.0


def clamp(v, lo=0.0, hi=100.0):
    return max(lo, min(hi, v))


def unique_keep_order(values):
    seen = set()
    out = []
    for v in values:
        if v in seen:
            continue
        seen.add(v)
        out.append(v)
    return out


# ============================================================
# Optional Semrush traffic / authority enrichment
# ============================================================
# We accept fuzzy header aliases so exports from Bulk Analysis / Domain Overview
# can be dropped directly into traffic/ without manual renaming.
DOMAIN_ALIASES = {
    "domain", "root domain", "url", "target", "website", "host", "host name", "hostname"
}
AUTHORITY_ALIASES = {
    "authority score", "as", "domain authority score", "authority"
}
MONTHLY_VISITS_ALIASES = {
    "monthly visits", "visits", "monthly visit", "total visits"
}
ORGANIC_TRAFFIC_ALIASES = {
    "organic traffic", "organic search traffic", "search traffic", "organic traffic estimate"
}
ORGANIC_KEYWORDS_ALIASES = {
    "organic keywords", "keywords", "organic keyword"
}


def pick_header(headers, aliases):
    normalized = {normalize_header(h): h for h in headers}
    for alias in aliases:
        if normalize_header(alias) in normalized:
            return normalized[normalize_header(alias)]
    # fuzzy contains fallback, conservative
    for nh, original in normalized.items():
        for alias in aliases:
            a = normalize_header(alias)
            if a and (nh == a or nh.endswith(" " + a) or nh.startswith(a + " ")):
                return original
    return None


def read_csv_or_tsv(path):
    attempts = [
        ("utf-8-sig", "\t" if path.lower().endswith(".tsv") else ","),
        ("utf-16", "\t"),
        ("utf-8", "\t" if path.lower().endswith(".tsv") else ","),
        ("latin1", ","),
    ]
    last = None
    for encoding, delimiter in attempts:
        try:
            with open(path, "r", encoding=encoding, newline="") as f:
                reader = csv.DictReader(f, delimiter=delimiter)
                if not reader.fieldnames or len(reader.fieldnames) < 2:
                    continue
                return [dict(r) for r in reader], list(reader.fieldnames)
        except Exception as exc:
            last = exc
    raise ValueError(f"无法读取 {path}: {last}")


def read_xlsx_rows(path):
    if not HAS_OPENPYXL:
        raise RuntimeError("读取 xlsx enrichment 需要 openpyxl")
    wb = load_workbook(path, read_only=True, data_only=True)
    # Prefer the first non-empty sheet.
    for ws in wb.worksheets:
        rows = ws.iter_rows(values_only=True)
        try:
            first = next(rows)
        except StopIteration:
            continue
        headers = [str(x or "").strip() for x in first]
        if len([h for h in headers if h]) < 2:
            continue
        out = []
        for values in rows:
            record = {}
            for i, h in enumerate(headers):
                if not h:
                    continue
                record[h] = values[i] if i < len(values) else None
            out.append(record)
        wb.close()
        return out, headers
    wb.close()
    return [], []


def load_semrush_enrichment():
    """
    Return mapping:
      domain -> {
          authority_score: float|None,
          monthly_visits: float|None,
          organic_traffic: float|None,
          organic_keywords: float|None,
          source_files: set[str]
      }

    Multiple exports are merged using MAX for numeric metrics because a domain may
    appear in multiple Semrush files/country databases. We keep source filenames.
    """
    os.makedirs(TRAFFIC_DIR, exist_ok=True)
    files = sorted(
        glob.glob(os.path.join(TRAFFIC_DIR, "*.csv"))
        + glob.glob(os.path.join(TRAFFIC_DIR, "*.tsv"))
        + glob.glob(os.path.join(TRAFFIC_DIR, "*.xlsx"))
    )

    result = {}
    import_log = []

    for path in files:
        try:
            if path.lower().endswith(".xlsx"):
                rows, headers = read_xlsx_rows(path)
            else:
                rows, headers = read_csv_or_tsv(path)
        except Exception as exc:
            import_log.append((os.path.basename(path), "ERROR", str(exc)))
            continue

        if not rows or not headers:
            import_log.append((os.path.basename(path), "EMPTY", "无数据"))
            continue

        h_domain = pick_header(headers, DOMAIN_ALIASES)
        h_as = pick_header(headers, AUTHORITY_ALIASES)
        h_visits = pick_header(headers, MONTHLY_VISITS_ALIASES)
        h_org = pick_header(headers, ORGANIC_TRAFFIC_ALIASES)
        h_kw = pick_header(headers, ORGANIC_KEYWORDS_ALIASES)

        if not h_domain:
            import_log.append((os.path.basename(path), "SKIP", "未识别 Domain/URL 列"))
            continue

        imported = 0
        for row in rows:
            domain = clean_domain(row.get(h_domain))
            if not domain:
                continue

            rec = result.setdefault(domain, {
                "authority_score": None,
                "monthly_visits": None,
                "organic_traffic": None,
                "organic_keywords": None,
                "source_files": set(),
            })

            for key, header in [
                ("authority_score", h_as),
                ("monthly_visits", h_visits),
                ("organic_traffic", h_org),
                ("organic_keywords", h_kw),
            ]:
                if not header:
                    continue
                raw = row.get(header)
                if raw is None or str(raw).strip() == "":
                    continue
                value = safe_float(raw, None)
                if value is None:
                    continue
                if rec[key] is None:
                    rec[key] = value
                else:
                    rec[key] = max(rec[key], value)

            rec["source_files"].add(os.path.basename(path))
            imported += 1

        import_log.append((os.path.basename(path), "OK", f"读取 {imported} 行"))

    for rec in result.values():
        rec["source_files"] = sorted(rec["source_files"])

    return result, import_log


# ============================================================
# Load backlink intelligence database
# ============================================================
def load_backlinks():
    if not os.path.exists(DB_FILE):
        raise FileNotFoundError(
            f"未找到 {DB_FILE}\n"
            "请先运行 link-read.py，生成 semrush_backlink_intelligence.db。"
        )

    conn = sqlite3.connect(DB_FILE)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    # Validate expected schema; do not mutate the database.
    cur.execute("PRAGMA table_info(backlinks)")
    cols = {r[1] for r in cur.fetchall()}
    required = {
        "competitor_domain", "ref_domain", "source_title", "source_url", "target_url",
        "anchor", "page_ascore", "external_links", "is_nofollow", "is_sponsored",
        "is_ugc", "is_sitewide", "is_lost", "first_seen", "last_seen"
    }
    missing = sorted(required - cols)
    if missing:
        conn.close()
        raise RuntimeError(
            "数据库不是当前 Semrush link-read.py 的 schema，缺少列：" + ", ".join(missing)
        )

    cur.execute("SELECT * FROM backlinks")
    rows = [dict(r) for r in cur.fetchall()]
    conn.close()
    return rows


def group_by_ref_domain(rows):
    grouped = defaultdict(list)
    for r in rows:
        domain = str(r.get("ref_domain") or "").strip().lower()
        if domain:
            grouped[domain].append(r)
    return grouped


# ============================================================
# Acquisition-path classifier: P0 / P1 / P2 / P3 / Drop
# ============================================================
# Drop is intentionally conservative. Low authority / no traffic alone never causes Drop.
TECHNICAL_HOST_PATTERNS = [
    "cloudfront.net", "akamaized.net", "akamaihd.net", "cdn.jsdelivr.net",
    "googleusercontent.com", "gstatic.com", "gravatar.com", "imgur.com",
    "imageshack.com", "twimg.com", "fbcdn.net", "doubleclick.net",
]

REDIRECT_HOSTS = {
    "bit.ly", "t.co", "tinyurl.com", "goo.gl", "ow.ly", "buff.ly",
    "lnkd.in", "rebrand.ly", "cutt.ly", "shorturl.at"
}

TECHNICAL_PATH_PATTERNS = [
    "/wp-content/uploads/", "/wp-includes/", "/static/", "/assets/",
    "/cdn-cgi/", "/images/", "/image/", "/img/", "/fonts/", "/scripts/"
]

ASSET_EXTENSIONS = {
    ".jpg", ".jpeg", ".png", ".gif", ".webp", ".svg", ".ico",
    ".css", ".js", ".woff", ".woff2", ".ttf", ".eot", ".mp3", ".mp4",
    ".webm", ".avi", ".mov", ".zip", ".rar", ".7z"
}

P0_STRONG_PATTERNS = [
    "add-listing", "add_listing", "addlisting", "add-company", "add-business",
    "add-site", "add-website", "submit-site", "submit-website", "submit-company",
    "submit-business", "submit-software", "submit-tool", "submit-product",
    "claim-profile", "claim-listing", "create-listing", "create-profile",
    "list-your-business", "list-your-company", "list-your-site", "get-listed",
    "add supplier", "add vendor", "submit supplier", "submit vendor",
]

P0_DIRECTORY_PATTERNS = [
    "/directory/", "/directories/", "/listing/", "/listings/", "/companies/",
    "/company/", "/suppliers/", "/supplier/", "/vendors/", "/vendor/",
    "/businesses/", "/profiles/", "/profile/", "/software/", "/tools/"
]

P0_DOMAIN_HINTS = [
    "directory", "listings", "yellowpages", "hotfrog", "manta", "kompass",
    "capterra", "g2.com", "getapp", "trustradius", "saashub", "sourceforge",
    "producthunt", "alternativeto", "goodfirms", "clutch.co", "designrush"
]

P1_PATTERNS = [
    "contact", "contact-us", "contactus", "partner", "partners", "partnership",
    "become-a-partner", "partner-application", "vendor-application",
    "supplier-application", "apply", "application", "affiliate", "affiliates",
    "write-for-us", "writeforus", "guest-post", "guestpost", "contribute",
    "contributor", "submit-article", "submit-post", "editorial-guidelines",
    "submission-guidelines", "advertise", "advertising", "sponsor", "sponsorship",
    "media-kit", "press-contact", "resource-submission", "suggest-a-tool"
]

P3_PATTERNS = [
    "/integrations/", "/integration/", "integration-partner", "technology-partner",
    "developer", "developers", "api-partner", "app-marketplace", "marketplace/app",
    "marketplace/apps", "app-store", "plugin-directory", "extensions",
    "association", "membership", "member-directory", "research-partner",
    "data-partner", "press-room", "newsroom"
]

P3_APP_DOMAINS = {
    "apps.shopify.com", "zapier.com", "make.com", "slack.com", "hubspot.com",
    "salesforce.com", "wordpress.org", "woocommerce.com", "microsoft.com",
    "chromewebstore.google.com", "addons.mozilla.org"
}

P3_MEDIA_DOMAINS = {
    "forbes.com", "techcrunch.com", "entrepreneur.com", "businessinsider.com",
    "wired.com", "theverge.com", "venturebeat.com", "fastcompany.com",
    "inc.com", "reuters.com", "bloomberg.com"
}

EDITORIAL_PATTERNS = [
    "/blog/", "/blogs/", "/article/", "/articles/", "/post/", "/posts/",
    "/news/", "/guide/", "/guides/", "/resources/", "/resource/", "/academy/",
    "best-", "top-", "review", "reviews", "comparison", "compare", "vs-",
    "alternatives", "recommended", "how-to", "case-study"
]


def text_blob(domain, rows):
    parts = [domain]
    for r in rows:
        parts.extend([
            str(r.get("source_title") or ""),
            str(r.get("source_url") or ""),
            str(r.get("anchor") or ""),
        ])
    return "\n".join(parts).lower()


def match_patterns(blob, patterns):
    return [p for p in patterns if p.lower() in blob]


def detect_drop(domain, rows):
    reasons = []

    # Same-domain source is not a replicable external backlink opportunity.
    competitor_domains = {str(r.get("competitor_domain") or "").lower() for r in rows}
    if domain in competitor_domains:
        reasons.append("来源域名=竞品自身域名（非外部机会）")

    if domain in REDIRECT_HOSTS:
        reasons.append("短链/跳转域名")

    if any(domain == h or domain.endswith("." + h) for h in TECHNICAL_HOST_PATTERNS):
        reasons.append("CDN/静态资源托管域名")

    source_urls = [str(r.get("source_url") or "") for r in rows]
    if source_urls:
        asset_like = 0
        technical_path_like = 0
        for u in source_urls:
            path = url_path(u)
            ext = os.path.splitext(path)[1].lower()
            if ext in ASSET_EXTENSIONS:
                asset_like += 1
            if any(p in path for p in TECHNICAL_PATH_PATTERNS):
                technical_path_like += 1

        if asset_like == len(source_urls):
            reasons.append("全部样例都是图片/脚本/字体/压缩包等静态文件")
        elif technical_path_like == len(source_urls) and asset_like >= max(1, len(source_urls) // 2):
            reasons.append("全部样例均位于静态资源路径")

    if reasons:
        return True, reasons
    return False, []


def classify_priority(domain, rows):
    """
    Heuristic pre-classification based only on observed backlink evidence.
    It is intentionally auditable: returns matched evidence and confidence.

    Final web verification can later overwrite the editable '最终优先级' column.
    """
    is_drop, drop_reasons = detect_drop(domain, rows)
    if is_drop:
        return {
            "priority": "Drop",
            "confidence": 0.98,
            "method": "放弃：技术/结构性不可执行",
            "action": "不投入人工外联；保留作审计证据。如误判可人工改回 P0-P3。",
            "evidence": "；".join(drop_reasons),
        }

    blob = text_blob(domain, rows)
    p0_strong = match_patterns(blob, P0_STRONG_PATTERNS)
    p0_dir = match_patterns(blob, P0_DIRECTORY_PATTERNS)
    p0_domain = match_patterns(domain, P0_DOMAIN_HINTS)
    p1 = match_patterns(blob, P1_PATTERNS)
    p3 = match_patterns(blob, P3_PATTERNS)
    editorial = match_patterns(blob, EDITORIAL_PATTERNS)

    # TLD-level strategic signal: do not assume easy acquisition for edu/gov.
    strategic_tld = bool(re.search(r"\.(edu|gov)(\.[a-z]{2})?$", domain))
    app_domain = any(domain == d or domain.endswith("." + d) for d in P3_APP_DOMAINS)
    media_domain = any(domain == d or domain.endswith("." + d) for d in P3_MEDIA_DOMAINS)

    # Strategic overrides generic directory/contact hints because execution cost is fundamentally different.
    if app_domain or strategic_tld or media_domain or p3:
        evidence = []
        if app_domain:
            evidence.append("生态/App Marketplace 域名")
        if strategic_tld:
            evidence.append("EDU/GOV 高门槛来源")
        if media_domain:
            evidence.append("头部媒体域名")
        if p3:
            evidence.append("战略关键词: " + ", ".join(unique_keep_order(p3)[:6]))
        return {
            "priority": "P3",
            "confidence": 0.88 if (app_domain or media_domain or strategic_tld) else 0.76,
            "method": "战略合作 / Integration / PR / 生态入驻",
            "action": "先研究真实合作机制；需要定制资产、集成、PR、研究数据或高层商务，不按普通冷邮件批量做。",
            "evidence": "；".join(evidence),
        }

    if p0_strong:
        return {
            "priority": "P0",
            "confidence": 0.94,
            "method": "Self-serve 提交 / 注册 / Claim / Add Listing",
            "action": "优先立即打开官方入口，注册账号并提交 Arkswift 公司/产品/供应商主页；完成后记录 Live URL。",
            "evidence": "强 P0 信号: " + ", ".join(unique_keep_order(p0_strong)[:8]),
        }

    # Directory/profile structure without explicit Add/Submit page: still likely P0, but requires verification.
    if p0_dir or p0_domain:
        evidence_parts = []
        if p0_dir:
            evidence_parts.append("目录/Profile 路径: " + ", ".join(unique_keep_order(p0_dir)[:6]))
        if p0_domain:
            evidence_parts.append("目录型域名指纹: " + ", ".join(unique_keep_order(p0_domain)[:4]))
        return {
            "priority": "P0",
            "confidence": 0.72,
            "method": "疑似 Self-serve Directory/Profile",
            "action": "先查 Add Listing / Submit / Register / Claim Profile。若无自助入口，再降到 P1 官方 Contact。",
            "evidence": "；".join(evidence_parts),
        }

    if p1:
        return {
            "priority": "P1",
            "confidence": 0.83,
            "method": "官方 Contact / Application / Partner / Contributor",
            "action": "优先使用官方申请页/Contact Form/Partner Program；只有找不到官方入口时才转 P2 冷邮件。",
            "evidence": "官方入口信号: " + ", ".join(unique_keep_order(p1)[:8]),
        }

    # Default actionable web/editorial opportunity = P2.
    if editorial:
        return {
            "priority": "P2",
            "confidence": 0.74,
            "method": "冷邮件：编辑更新 / Resource / Guest Post / Listicle",
            "action": "定位站点编辑/内容负责人，优先针对现有文章或资源页提出具体更新理由，而不是泛化群发。",
            "evidence": "内容型来源: " + ", ".join(unique_keep_order(editorial)[:8]),
        }

    return {
        "priority": "P2",
        "confidence": 0.55,
        "method": "冷邮件：需先人工核验获取机制",
        "action": "默认进入人工/AI核验：找官方提交入口；若不存在，则寻找编辑/商务邮箱进行个性化冷外联。",
        "evidence": "未发现明确 P0/P1/P3 指纹，保守归入 P2 待核验",
    }


# ============================================================
# Intelligence aggregation + machine scoring
# ============================================================
def summarize_domain(domain, rows, enrichment):
    live = [r for r in rows if not safe_int(r.get("is_lost"), 0)]
    competitors = sorted({str(r.get("competitor_domain") or "") for r in rows if r.get("competitor_domain")})
    source_pages = {str(r.get("source_url") or "") for r in rows if r.get("source_url")}
    target_pages = {str(r.get("target_url") or "") for r in rows if r.get("target_url")}

    page_as = [safe_float(r.get("page_ascore"), 0) for r in rows]
    live_page_as = [safe_float(r.get("page_ascore"), 0) for r in live]
    external_links = [safe_int(r.get("external_links"), 0) for r in rows]

    first_seen = sorted(str(r.get("first_seen") or "") for r in rows if r.get("first_seen"))
    last_seen = sorted(str(r.get("last_seen") or "") for r in rows if r.get("last_seen"))

    comp_counts = Counter(str(r.get("competitor_domain") or "") for r in rows)

    enrich = enrichment.get(domain, {})
    domain_as = enrich.get("authority_score")
    monthly_visits = enrich.get("monthly_visits")
    organic_traffic = enrich.get("organic_traffic")
    organic_keywords = enrich.get("organic_keywords")
    enrichment_sources = enrich.get("source_files", [])

    samples = []
    ordered = sorted(
        rows,
        key=lambda r: (
            safe_int(r.get("is_lost"), 0),
            -safe_float(r.get("page_ascore"), 0),
            str(r.get("source_url") or "")
        )
    )
    for r in ordered:
        attrs = []
        if is_follow(r):
            attrs.append("Follow")
        if safe_int(r.get("is_nofollow"), 0):
            attrs.append("Nofollow")
        if safe_int(r.get("is_sponsored"), 0):
            attrs.append("Sponsored")
        if safe_int(r.get("is_ugc"), 0):
            attrs.append("UGC")
        if safe_int(r.get("is_sitewide"), 0):
            attrs.append("Sitewide")
        status = "LOST" if safe_int(r.get("is_lost"), 0) else "LIVE"
        samples.append(
            f"[{r.get('competitor_domain','')}] [{status}] Page AS {safe_float(r.get('page_ascore'),0):.0f} | "
            f"{r.get('source_url','')} --[{r.get('anchor') or '无锚文本'}]--> {r.get('target_url','')} "
            f"({'/'.join(attrs) if attrs else 'No special attribute'})"
        )
    samples = unique_keep_order(samples)[:MAX_SAMPLE_LINKS]

    summary = {
        "domain": domain,
        "alpha": len(competitors),
        "competitors": competitors,
        "competitor_link_counts": comp_counts,
        "backlinks": len(rows),
        "live_backlinks": len(live),
        "live_rate": pct(len(live), len(rows)),
        "source_pages": len(source_pages),
        "target_pages": len(target_pages),
        "max_page_as": max(page_as) if page_as else 0,
        "avg_page_as": mean(page_as) if page_as else 0,
        "live_avg_page_as": mean(live_page_as) if live_page_as else 0,
        "high_page_as_rate": pct(sum(v >= HIGH_PAGE_AS_THRESHOLD for v in live_page_as), len(live_page_as)),
        "follow_rate": pct(sum(is_follow(r) for r in rows), len(rows)),
        "live_follow_rate": pct(sum(is_follow(r) for r in live), len(live)),
        "sitewide_rate": pct(sum(safe_int(r.get("is_sitewide"), 0) for r in rows), len(rows)),
        "sponsored_rate": pct(sum(safe_int(r.get("is_sponsored"), 0) for r in rows), len(rows)),
        "ugc_rate": pct(sum(safe_int(r.get("is_ugc"), 0) for r in rows), len(rows)),
        "avg_external_links": mean(external_links) if external_links else 0,
        "earliest_first_seen": first_seen[0] if first_seen else "",
        "latest_last_seen": last_seen[-1] if last_seen else "",
        "domain_authority_score": domain_as,
        "monthly_visits": monthly_visits,
        "organic_traffic": organic_traffic,
        "organic_keywords": organic_keywords,
        "enrichment_sources": enrichment_sources,
        "samples": samples,
        "rows": rows,
    }
    return summary


def alpha_component(alpha):
    # Retains the spirit of the old overlap score without letting overlap define acquisition path.
    if alpha >= 7:
        return 100
    if alpha == 6:
        return 92
    if alpha == 5:
        return 84
    if alpha == 4:
        return 72
    if alpha == 3:
        return 58
    if alpha == 2:
        return 40
    return 20


def traffic_component(traffic):
    """Semrush organic traffic score. None = missing/unknown, not zero."""
    if traffic is None:
        return None
    traffic = max(0.0, safe_float(traffic, 0))
    if traffic == 0:
        return 0
    if traffic < 50:
        return 55
    if traffic < 500:
        return 70
    if traffic < 5_000:
        return 82
    if traffic < 50_000:
        return 92
    return 100


def visits_component(visits):
    if visits is None:
        return None
    visits = max(0.0, safe_float(visits, 0))
    if visits == 0:
        return 0
    # Smooth log scaling. 1k ~= 60; 10k ~= 80; 100k+ approaches 100.
    return clamp(20 + 20 * math.log10(visits + 1), 0, 100)


def compute_machine_score(d):
    """
    Dynamic weighted score.

    Missing optional Semrush traffic metrics are removed from the denominator,
    so a domain is not punished simply because the user has not enriched it yet.
    """
    authority = d["domain_authority_score"]
    authority_signal = safe_float(authority, 0) if authority is not None else d["max_page_as"]

    components = [
        ("Authority", clamp(authority_signal), 0.30),
        ("Alpha", alpha_component(d["alpha"]), 0.20),
        ("Live", clamp(d["live_rate"] * 100), 0.12),
        ("Follow", clamp(d["live_follow_rate"] * 100), 0.10),
        ("Avg Page AS", clamp(d["live_avg_page_as"]), 0.08),
        ("High Page AS", clamp(d["high_page_as_rate"] * 100), 0.05),
    ]

    org_score = traffic_component(d["organic_traffic"])
    visit_score = visits_component(d["monthly_visits"])
    if org_score is not None:
        components.append(("Organic Traffic", org_score, 0.10))
    if visit_score is not None:
        components.append(("Monthly Visits", visit_score, 0.05))

    weighted_sum = sum(score * weight for _, score, weight in components)
    weight_sum = sum(weight for _, _, weight in components)
    base = weighted_sum / weight_sum if weight_sum else 0

    # Structural penalties; not enough to turn a legitimate domain into Drop.
    penalty = 0.0
    if d["sitewide_rate"] >= 0.50:
        penalty += 8
    elif d["sitewide_rate"] >= 0.20:
        penalty += 4

    if d["sponsored_rate"] >= 0.50:
        penalty += 6
    elif d["sponsored_rate"] >= 0.20:
        penalty += 3

    if d["ugc_rate"] >= 0.70:
        penalty += 4

    # History-only domains are still valid prospects, but less urgent.
    if d["live_backlinks"] == 0:
        penalty += 8

    score = round(clamp(base - penalty), 1)
    breakdown = "; ".join(f"{name}={score_:.0f}×{weight:.0%}" for name, score_, weight in components)
    if penalty:
        breakdown += f"; Penalty=-{penalty:.0f}"
    return score, breakdown


# ============================================================
# Build action queue records
# ============================================================
def build_action_queue(rows, enrichment):
    grouped = group_by_ref_domain(rows)
    output = []

    for domain, domain_rows in grouped.items():
        d = summarize_domain(domain, domain_rows, enrichment)
        classification = classify_priority(domain, domain_rows)
        score, score_breakdown = compute_machine_score(d)

        if classification["priority"] == "Drop":
            # Keep audit visibility but force Drop to the bottom irrespective of score.
            effective_score = min(score, 25.0)
        else:
            effective_score = score

        total_links_text = (
            f"总计:{d['backlinks']} | "
            + ", ".join(f"{k}:{v}" for k, v in sorted(d["competitor_link_counts"].items()))
        )

        traffic_status = "已补充"
        if d["domain_authority_score"] is None and d["monthly_visits"] is None and d["organic_traffic"] is None:
            traffic_status = "未补充"
        elif d["organic_traffic"] is None:
            traffic_status = "部分补充"

        output.append({
            "priority": classification["priority"],
            "priority_label": PRIORITY_LABEL[classification["priority"]],
            "priority_rank": PRIORITY_RANK[classification["priority"]],
            "domain": domain,
            "machine_score": effective_score,
            "score_breakdown": score_breakdown,
            "classification_confidence": classification["confidence"],
            "machine_method": classification["method"],
            "action_suggested": classification["action"],
            "classification_evidence": classification["evidence"],
            "alpha": d["alpha"],
            "competitors": ", ".join(d["competitors"]),
            "total_links": total_links_text,
            "backlinks": d["backlinks"],
            "live_backlinks": d["live_backlinks"],
            "live_rate": d["live_rate"],
            "source_pages": d["source_pages"],
            "target_pages": d["target_pages"],
            "domain_authority_score": d["domain_authority_score"],
            "max_page_as": d["max_page_as"],
            "avg_page_as": d["avg_page_as"],
            "live_avg_page_as": d["live_avg_page_as"],
            "high_page_as_rate": d["high_page_as_rate"],
            "organic_traffic": d["organic_traffic"],
            "monthly_visits": d["monthly_visits"],
            "organic_keywords": d["organic_keywords"],
            "traffic_status": traffic_status,
            "traffic_source": ", ".join(d["enrichment_sources"]),
            "follow_rate": d["follow_rate"],
            "live_follow_rate": d["live_follow_rate"],
            "sitewide_rate": d["sitewide_rate"],
            "sponsored_rate": d["sponsored_rate"],
            "ugc_rate": d["ugc_rate"],
            "avg_external_links": d["avg_external_links"],
            "earliest_first_seen": d["earliest_first_seen"],
            "latest_last_seen": d["latest_last_seen"],
            "sample_links": "\n\n".join(d["samples"]),
        })

    # Priority decides workflow. Score decides order INSIDE priority.
    output.sort(
        key=lambda x: (
            x["priority_rank"],
            -x["machine_score"],
            -(x["domain_authority_score"] if x["domain_authority_score"] is not None else x["max_page_as"]),
            -(x["organic_traffic"] if x["organic_traffic"] is not None else -1),
            -x["alpha"],
            x["domain"],
        )
    )
    return output


# ============================================================
# Excel / CSV output
# ============================================================
def add_dropdown(ws, cell_range, values):
    formula = '"' + ",".join(values) + '"'
    dv = DataValidation(type="list", formula1=formula, allow_blank=True)
    ws.add_data_validation(dv)
    dv.add(cell_range)


def style_header(cell, fill):
    cell.font = Font(bold=True, color=COLOR_WHITE)
    cell.fill = PatternFill("solid", fgColor=fill)
    cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)


def generate_excel(queue, enrichment_log):
    if not HAS_OPENPYXL:
        raise RuntimeError("未安装 openpyxl。请先运行：pip install openpyxl")

    os.makedirs(REPORT_DIR, exist_ok=True)
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    out_file = os.path.join(REPORT_DIR, f"Backlink_Action_Queue_P0-P3_{date_str}.xlsx")

    wb = Workbook()
    ws = wb.active
    ws.title = "外链可执行总表"
    ws.sheet_view.showGridLines = False
    ws.freeze_panes = "C2"

    headers = [
        # Workflow classification
        ("机器优先级", COLOR_MACHINE),
        ("目标域名 (Domain)", COLOR_MACHINE),
        ("🤖机器评分 (0-100)", COLOR_SCORE),
        ("机器分组成", COLOR_MACHINE),
        ("机器获取方式", COLOR_MACHINE),
        ("建议动作", COLOR_MACHINE),
        ("分类置信度", COLOR_MACHINE),
        ("分类依据", COLOR_MACHINE),

        # Semrush intelligence
        ("竞品重合度 Alpha", COLOR_INTEL),
        ("被哪些竞品获取", COLOR_INTEL),
        ("该域名外链分布", COLOR_INTEL),
        ("Backlinks", COLOR_INTEL),
        ("Live Backlinks", COLOR_INTEL),
        ("Live 占比", COLOR_INTEL),
        ("来源页面数", COLOR_INTEL),
        ("指向目标页数", COLOR_INTEL),
        ("Semrush 域名 Authority Score", COLOR_INTEL),
        ("最高来源页 Page AS", COLOR_INTEL),
        ("平均来源页 Page AS", COLOR_INTEL),
        ("Live 平均 Page AS", COLOR_INTEL),
        (f"Live 高 Page AS 占比 (≥{HIGH_PAGE_AS_THRESHOLD})", COLOR_INTEL),
        ("Semrush Organic Traffic", COLOR_INTEL),
        ("Semrush Monthly Visits", COLOR_INTEL),
        ("Semrush Organic Keywords", COLOR_INTEL),
        ("流量补充状态", COLOR_INTEL),
        ("流量数据来源文件", COLOR_INTEL),
        ("Follow 占比", COLOR_INTEL),
        ("Live Follow 占比", COLOR_INTEL),
        ("Sitewide 占比", COLOR_INTEL),
        ("Sponsored 占比", COLOR_INTEL),
        ("UGC 占比", COLOR_INTEL),
        ("来源页平均 External Links", COLOR_INTEL),
        ("最早 First Seen", COLOR_INTEL),
        ("最近 Last Seen", COLOR_INTEL),
        ("对标链接样例", COLOR_INTEL),

        # AI verification handoff
        ("🧠AI: 最终优先级", COLOR_AI),
        ("🧠AI: 业务相关性评分 (0-100)", COLOR_AI),
        ("🧠AI: 核验后的获取方式", COLOR_AI),
        ("🧠AI: 核验结论 / 为什么", COLOR_AI),
        ("🧠AI: Pitch/提交备注", COLOR_AI),

        # Human execution
        ("🧑‍💻联系邮箱", COLOR_HUMAN),
        ("🧑‍💻官方获取入口 URL", COLOR_HUMAN),
        ("🧑‍💻实际 Live URL", COLOR_HUMAN),
        ("🏆最终总分", COLOR_SCORE),
        ("🧑‍💻审阅状态", COLOR_HUMAN),
        ("🧑‍💻当前状态", COLOR_HUMAN),
        ("🧑‍💻最后核验日期", COLOR_HUMAN),
        ("🧑‍💻执行备注", COLOR_HUMAN),
    ]

    ws.append([h[0] for h in headers])
    for col_idx, (_, fill) in enumerate(headers, 1):
        style_header(ws.cell(1, col_idx), fill)
    ws.row_dimensions[1].height = 42

    # Column index map for formulas / validation.
    col_map = {name: idx + 1 for idx, (name, _) in enumerate(headers)}

    for row_idx, d in enumerate(queue, start=2):
        ws.append([
            d["priority_label"],
            d["domain"],
            d["machine_score"],
            d["score_breakdown"],
            d["machine_method"],
            d["action_suggested"],
            d["classification_confidence"],
            d["classification_evidence"],
            d["alpha"],
            d["competitors"],
            d["total_links"],
            d["backlinks"],
            d["live_backlinks"],
            d["live_rate"],
            d["source_pages"],
            d["target_pages"],
            d["domain_authority_score"],
            round(d["max_page_as"], 1),
            round(d["avg_page_as"], 1),
            round(d["live_avg_page_as"], 1),
            d["high_page_as_rate"],
            d["organic_traffic"],
            d["monthly_visits"],
            d["organic_keywords"],
            d["traffic_status"],
            d["traffic_source"],
            d["follow_rate"],
            d["live_follow_rate"],
            d["sitewide_rate"],
            d["sponsored_rate"],
            d["ugc_rate"],
            round(d["avg_external_links"], 1),
            d["earliest_first_seen"],
            d["latest_last_seen"],
            d["sample_links"],
            "",  # AI final priority
            "",  # AI relevance
            "",  # AI method
            "",  # AI conclusion
            "",  # AI pitch
            "",  # email
            "",  # official entry URL
            "",  # live URL
            "",  # final score formula below
            "待审阅",
            "未开始",
            "",
            "",
        ])

        # Priority color stripe in column A.
        pr_fill = PRIORITY_COLORS[d["priority"]]
        ws.cell(row_idx, 1).fill = PatternFill("solid", fgColor=pr_fill)
        ws.cell(row_idx, 1).font = Font(bold=True, color=COLOR_WHITE)

        # Final score = 90% machine + 10% AI relevance if numeric;
        # if AI relevance is blank, show machine score instead of artificially reducing it.
        machine_col = get_column_letter(col_map["🤖机器评分 (0-100)"])
        ai_rel_col = get_column_letter(col_map["🧠AI: 业务相关性评分 (0-100)"])
        total_col = col_map["🏆最终总分"]
        formula = (
            f'=IF(ISNUMBER({ai_rel_col}{row_idx}),' 
            f'({machine_col}{row_idx}*0.9)+({ai_rel_col}{row_idx}*0.1),'
            f'{machine_col}{row_idx})'
        )
        ws.cell(row_idx, total_col, value=formula)
        ws.cell(row_idx, total_col).font = Font(bold=True, color=COLOR_RED)

        # Number formats.
        for col_name in [
            "Live 占比", f"Live 高 Page AS 占比 (≥{HIGH_PAGE_AS_THRESHOLD})",
            "Follow 占比", "Live Follow 占比", "Sitewide 占比",
            "Sponsored 占比", "UGC 占比", "分类置信度"
        ]:
            ws.cell(row_idx, col_map[col_name]).number_format = "0.0%"

        for col_name in [
            "Semrush Organic Traffic", "Semrush Monthly Visits", "Semrush Organic Keywords",
            "Backlinks", "Live Backlinks", "来源页面数", "指向目标页数"
        ]:
            ws.cell(row_idx, col_map[col_name]).number_format = "#,##0"

        # Text-heavy wrapping.
        for col_name in [
            "机器分组成", "机器获取方式", "建议动作", "分类依据", "被哪些竞品获取",
            "该域名外链分布", "流量数据来源文件", "对标链接样例",
            "🧠AI: 核验结论 / 为什么", "🧠AI: Pitch/提交备注", "🧑‍💻执行备注"
        ]:
            ws.cell(row_idx, col_map[col_name]).alignment = Alignment(wrap_text=True, vertical="top")

    last_row = max(2, ws.max_row)
    ws.auto_filter.ref = f"A1:{get_column_letter(ws.max_column)}{ws.max_row}"

    # Dropdowns: editable final priority and workflow states.
    add_dropdown(ws, f"{get_column_letter(col_map['🧠AI: 最终优先级'])}2:{get_column_letter(col_map['🧠AI: 最终优先级'])}{last_row}",
                 ["P0", "P1", "P2", "P3", "Drop"])
    add_dropdown(ws, f"{get_column_letter(col_map['🧑‍💻审阅状态'])}2:{get_column_letter(col_map['🧑‍💻审阅状态'])}{last_row}",
                 ["待审阅", "已核验", "需复核", "跳过"])
    add_dropdown(ws, f"{get_column_letter(col_map['🧑‍💻当前状态'])}2:{get_column_letter(col_map['🧑‍💻当前状态'])}{last_row}",
                 ["未开始", "研究中", "待提交", "已提交", "等待审核", "已上线", "已拒绝", "无入口", "暂停", "Drop"])

    # Conditional formatting on machine score.
    score_letter = get_column_letter(col_map["🤖机器评分 (0-100)"])
    ws.conditional_formatting.add(
        f"{score_letter}2:{score_letter}{last_row}",
        CellIsRule(operator="greaterThanOrEqual", formula=["80"], fill=PatternFill("solid", fgColor="C6EFCE"))
    )
    ws.conditional_formatting.add(
        f"{score_letter}2:{score_letter}{last_row}",
        CellIsRule(operator="lessThan", formula=["40"], fill=PatternFill("solid", fgColor="FCE4D6"))
    )

    # Practical widths: no single column should make the workbook unusable.
    widths = {
        1: 31, 2: 28, 3: 15, 4: 55, 5: 38, 6: 55, 7: 13, 8: 55,
        9: 14, 10: 45, 11: 48, 12: 12, 13: 14, 14: 12, 15: 13, 16: 13,
        17: 20, 18: 18, 19: 18, 20: 18, 21: 19, 22: 18, 23: 18, 24: 18,
        25: 15, 26: 36, 27: 13, 28: 15, 29: 13, 30: 14, 31: 12, 32: 18,
        33: 14, 34: 14, 35: 90, 36: 18, 37: 22, 38: 34, 39: 55, 40: 50,
        41: 28, 42: 35, 43: 35, 44: 14, 45: 16, 46: 18, 47: 16, 48: 45,
    }
    for idx, width in widths.items():
        ws.column_dimensions[get_column_letter(idx)].width = width

    thin = Side(style="thin", color="D9E1F2")
    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = Alignment(
                vertical="top",
                wrap_text=cell.alignment.wrap_text if cell.alignment else False
            )
            cell.border = Border(bottom=thin)

    # --------------------------------------------------------
    # Sheet 2: workflow summary
    # --------------------------------------------------------
    ws2 = wb.create_sheet("优先级说明")
    ws2.sheet_view.showGridLines = False
    ws2.append(["优先级", "核心定义", "典型获取方式", "关键原则"])
    for c in ws2[1]:
        style_header(c, COLOR_DARK)

    rules = [
        ["P0", "马上可以执行的 Self-serve 机会", "注册 / Add Listing / Submit / Claim Profile / Company Page", "先做，不因为 AS/流量低就自动降级"],
        ["P1", "存在明确官方入口，但通常需要审核/联系", "Contact / Partner / Vendor / Supplier / Affiliate / Contributor / Application", "官方 Application > 官方 Contact Form > 官方部门邮箱 > 通用邮箱"],
        ["P2", "没有明显官方入口，需要主动外联", "编辑更新 / Resource Page / Listicle / Guest Post / Review / Cold Email", "按具体页面和竞品链接样例做个性化 Pitch"],
        ["P3", "高门槛、非批量、需要资产或商务协作", "Integration / App Marketplace / PR / Media / Association / Data Partnership", "价值可很高，但不应该挤占 P0 的即时执行队列"],
        ["Drop", "技术残留或结构性不可执行来源", "CDN / 图片 / JS / 字体 / 短链 / 竞品自身域", "低权重、零流量本身不是 Drop 条件"],
    ]
    for r in rules:
        ws2.append(r)
        ws2.cell(ws2.max_row, 1).fill = PatternFill("solid", fgColor=PRIORITY_COLORS[r[0]])
        ws2.cell(ws2.max_row, 1).font = Font(bold=True, color=COLOR_WHITE)

    ws2.append([])
    ws2.append(["机器评分字段", "说明", "缺失时如何处理", "是否决定 P0-P3"])
    for c in ws2[ws2.max_row]:
        style_header(c, COLOR_INTEL)
    score_rules = [
        ["Semrush 域名 Authority Score", "可从 Semrush Bulk Analysis/Domain Overview 补充的域名级权重", "缺失时回退到来源页最高 Page AS", "否，只用于层内排序"],
        ["Page AS", "当前 Backlinks 导出中的来源页面级 Authority Score", "原始 Semrush backlink 数据直接可用", "否"],
        ["Organic Traffic", "Semrush 估算自然搜索流量", "未导入时记为未知，不当作 0", "否"],
        ["Monthly Visits", "Semrush Traffic & Market 的月访问估算", "未导入时不参与分母", "否"],
        ["Alpha", "同一来源域名被多少个竞品获取", "始终可由 backlink 底库计算", "否"],
        ["Live/Follow/Sitewide/Sponsored/UGC", "外链当前存活与属性结构", "始终可由 backlink 底库计算", "否"],
    ]
    for r in score_rules:
        ws2.append(r)

    ws2.column_dimensions["A"].width = 28
    ws2.column_dimensions["B"].width = 60
    ws2.column_dimensions["C"].width = 50
    ws2.column_dimensions["D"].width = 28
    for row in ws2.iter_rows():
        for c in row:
            c.alignment = Alignment(wrap_text=True, vertical="top")

    # --------------------------------------------------------
    # Sheet 3: enrichment import log
    # --------------------------------------------------------
    ws3 = wb.create_sheet("Semrush流量补充")
    ws3.sheet_view.showGridLines = False
    ws3.append(["文件", "状态", "说明"])
    for c in ws3[1]:
        style_header(c, COLOR_DARK)
    if enrichment_log:
        for row in enrichment_log:
            ws3.append(list(row))
    else:
        ws3.append(["traffic/", "未检测到补充文件", "可直接放 Semrush Bulk Analysis / Domain Overview 导出的 CSV、TSV 或 XLSX。"])
    ws3.append([])
    ws3.append(["推荐可识别列", "Authority Score / Monthly Visits / Organic Traffic / Organic Keywords", "Domain 或 URL 列会自动识别并归一化为域名。"])
    ws3.column_dimensions["A"].width = 45
    ws3.column_dimensions["B"].width = 22
    ws3.column_dimensions["C"].width = 100
    for row in ws3.iter_rows():
        for c in row:
            c.alignment = Alignment(wrap_text=True, vertical="top")

    wb.save(out_file)
    return out_file


def generate_csv(queue):
    os.makedirs(REPORT_DIR, exist_ok=True)
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    out_file = os.path.join(REPORT_DIR, f"Backlink_Action_Queue_P0-P3_{date_str}.csv")

    headers = [
        "Priority", "Domain", "Machine Score", "Machine Method", "Action Suggested",
        "Classification Confidence", "Classification Evidence", "Alpha", "Competitors",
        "Backlinks", "Live Backlinks", "Source Pages", "Target Pages",
        "Domain Authority Score", "Max Page AS", "Avg Page AS",
        "Organic Traffic", "Monthly Visits", "Organic Keywords", "Traffic Status",
        "Follow Rate", "Sitewide Rate", "Sponsored Rate", "UGC Rate",
        "Earliest First Seen", "Latest Last Seen", "Sample Links"
    ]

    with open(out_file, "w", encoding="utf-8-sig", newline="") as f:
        w = csv.writer(f)
        w.writerow(headers)
        for d in queue:
            w.writerow([
                d["priority"], d["domain"], d["machine_score"], d["machine_method"],
                d["action_suggested"], d["classification_confidence"], d["classification_evidence"],
                d["alpha"], d["competitors"], d["backlinks"], d["live_backlinks"],
                d["source_pages"], d["target_pages"], d["domain_authority_score"],
                d["max_page_as"], d["avg_page_as"], d["organic_traffic"],
                d["monthly_visits"], d["organic_keywords"], d["traffic_status"],
                d["follow_rate"], d["sitewide_rate"], d["sponsored_rate"], d["ugc_rate"],
                d["earliest_first_seen"], d["latest_last_seen"], d["sample_links"]
            ])
    return out_file


def generate_enrichment_domain_list(queue):
    """
    Domains lacking Semrush domain-level AS/traffic are written one per line.
    In addition to a master list, create Semrush Bulk Analysis batches of <=200
    targets each, matching the current Bulk Analysis input limit.
    """
    os.makedirs(REPORT_DIR, exist_ok=True)
    date_str = datetime.datetime.now().strftime("%Y-%m-%d")
    out_file = os.path.join(REPORT_DIR, f"Semrush_Traffic_Enrichment_Domains_{date_str}.txt")
    missing = [
        d["domain"] for d in queue
        if d["priority"] != "Drop"
        and d["domain_authority_score"] is None
        and d["organic_traffic"] is None
        and d["monthly_visits"] is None
    ]
    with open(out_file, "w", encoding="utf-8") as f:
        for domain in missing:
            f.write(domain + "\n")

    batch_dir = os.path.join(REPORT_DIR, f"Semrush_Bulk_Batches_{date_str}")
    os.makedirs(batch_dir, exist_ok=True)
    batch_files = []
    for start in range(0, len(missing), 200):
        batch = missing[start:start + 200]
        batch_no = start // 200 + 1
        batch_file = os.path.join(batch_dir, f"batch_{batch_no:03d}.txt")
        with open(batch_file, "w", encoding="utf-8") as f:
            f.write("\n".join(batch))
            if batch:
                f.write("\n")
        batch_files.append(batch_file)

    return out_file, len(missing), batch_dir, len(batch_files)


# ============================================================
# CLI
# ============================================================
def print_summary(queue, enrichment_log, excel_file, csv_file, domain_file, missing_count, batch_dir, batch_count):
    counts = Counter(d["priority"] for d in queue)
    enriched = sum(d["traffic_status"] != "未补充" for d in queue)

    print("\n=== Arkswift Semrush Backlink Action Engine ===")
    print(f"数据库: {DB_FILE}")
    print(f"来源域名总数: {len(queue):,}")
    print("优先级分布:")
    for p in ["P0", "P1", "P2", "P3", "Drop"]:
        print(f"  {p}: {counts.get(p, 0):,}")
    print(f"已有 Semrush 域名级流量/AS 补充: {enriched:,}")
    print(f"仍待补充流量的可执行域名: {missing_count:,}")

    if enrichment_log:
        print("\ntraffic/ 导入日志:")
        for item in enrichment_log:
            print("  -", " | ".join(str(x) for x in item))

    print("\n输出:")
    print(f"  Excel: {excel_file}")
    print(f"  CSV:   {csv_file}")
    print(f"  待补流量域名: {domain_file}")
    print(f"  Semrush Bulk 批次: {batch_dir}  ({batch_count} 个批次，每批最多 200)")
    print("\n排序逻辑: P0 → P1 → P2 → P3 → Drop；每层内部按机器评分降序。")
    print("注意: P0-P3 是获取路径；机器评分是机会价值。两者不再混为一谈。")


def run():
    if not HAS_OPENPYXL:
        print("[错误] 请先安装 openpyxl: pip install openpyxl")
        return 1

    try:
        print("[1/4] 读取 Semrush backlink intelligence 数据库...")
        rows = load_backlinks()
        if not rows:
            print("[结束] 数据库中没有 backlink 行。请先运行 link-read.py。")
            return 0

        print("[2/4] 读取可选 Semrush Authority/Traffic 补充数据...")
        enrichment, enrichment_log = load_semrush_enrichment()

        print("[3/4] 生成 P0/P1/P2/P3/Drop 执行优先级与机器评分...")
        queue = build_action_queue(rows, enrichment)

        print("[4/4] 输出 Excel / CSV / Semrush 待补流量域名清单...")
        excel_file = generate_excel(queue, enrichment_log)
        csv_file = generate_csv(queue)
        domain_file, missing_count, batch_dir, batch_count = generate_enrichment_domain_list(queue)

        print_summary(queue, enrichment_log, excel_file, csv_file, domain_file, missing_count, batch_dir, batch_count)
        return 0

    except Exception as exc:
        print(f"\n[错误] {type(exc).__name__}: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(run())
